#!/usr/bin/bash

icebox --Ice.Config=icebox.config &  

gnome-terminal -- bash -c \
	"python3 main.py --Ice.Config=configs/main.config; bash"


gnome-terminal -- bash -c \
        "python3 authentication.py --Ice.Config=configs/authentication.config; bash"
